VOAM/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from website.views import *


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',Index),
    url(r'^AddCameraDevice/$',AddCameraDevice),
    url(r'^AddBasicInfo/$',AddBasicInfo),
    url(r'^UpdateCameraDevice/(?P<cameraID>\d*)/$',UpdateCameraDevice),
    url(r'^DelCameraDevice/(?P<cameraID>\d*)/$',DelCameraDevice),
    url(r'^CameraDevice/(?P<cameraID>\d*)/$',CameraDeviceID),
    url(r'^UpLoad/$',UpLoad),
]

website/forms.py
# _*_ coding:utf-8 _*_

from django import forms
from django.forms import ModelForm
from models import *

class AddCameraDeviceForm(forms.Form):
    pid = forms.CharField(required=False,label='编号') # required=False允许为空
    name = forms.CharField(label='名称')
    group_list = DeviceGroup.objects.all()
    # print group_list
    group = forms.ModelChoiceField(queryset=DeviceGroup.objects.all(),required=True,label=u'分组')
    region = forms.ModelChoiceField(queryset=DeviceRegion.objects.all(),required=True,label=u'摄像头所在区域')
    direction = forms.ModelChoiceField(queryset=CameraDirection.objects.all(),required=True,label=u'方向')
    ctype = forms.ModelChoiceField(queryset=CameraType.objects.all(),required=True,label=u'摄像头类别')
    brand = forms.ModelChoiceField(queryset=DeviceBrand.objects.all(),required=True,label=u'品牌')
    dtype = forms.ModelChoiceField(queryset=DeviceType.objects.all(),required=True,label=u'型号')
    ip = forms.GenericIPAddressField(protocol='ipv4',label=u'IP:')
    username = forms.CharField(required=False,label=u'帐号', widget=forms.TextInput(attrs={'class':'sp'}))
    password = forms.CharField(required=False,label=u'密码')
    gpslon = forms.CharField(required=False,label=u'经度')
    gpswei = forms.CharField(required=False,label=u'伟度')
    telecom = forms.ModelChoiceField(queryset=Telecom.objects.all(),required=True,label=u'运营商')
    nvrdevice = forms.ModelChoiceField(queryset=NVRDevice.objects.all(),required=True,label=u'后端设备')
    powersupply = forms.ModelChoiceField(queryset=PowerSupply.objects.all(),required=True,label=u'供电方式')
    powerid = forms.CharField(required=False,label=u'供电标识')
class UpdateCameraDeviceForm(forms.Form):
    class Meta:
        model = CameraDevice

class AddDeviceStatusForm(forms.Form):
    devicestatus = forms.CharField()
class AddDeviceGroupForm(forms.Form):
    devicegroup = forms.CharField()
class AddDeviceRegionForm(forms.Form):
    deviceregion = forms.CharField()
class AddCameraDirectionForm(forms.Form):
    cameradirection = forms.CharField()
class AddCameraTypeForm(forms.Form):
    cameratype = forms.CharField()
class AddDeviceBrandForm(forms.Form):
    devicebrand = forms.CharField()
class AddDeviceTypeForm(forms.Form):
    devicetype = forms.CharField()

templates/AddBasicInfo.html
{% extends "Master/muban.html" %}
{% block content %}

<body>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">设备状态</h3>
        </div>
        <div class="panel-body">
            <form action='/AddBasicInfo/' method="post">
        <span>状态名:</span>{{ devicestatusform.devicestatus }}
        <input class="btn btn-success" type="submit" value="添加"><span>{{ devicestatusstatus }}</span>
    </form>
        </div>
        <table style="text-align: center;width: 80%" class="table table-bordered">
            <tr>
                <td>ID</td>
                <td>名</td>
            </tr>
            {% for item in devicestatuslist %}
                <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.name}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">设备分组</h3>
        </div>
        <div class="panel-body">
            <form action='/AddBasicInfo/' method="post">
                <span>设备分组:</span>{{ devicegroupform.devicegroup }}
                <input class="btn btn-success" type="submit" value="添加"><span>{{ devicegroupstatus }}</span>
            </form>
        </div>
                <table style="text-align: center;width: 80%" class="table table-bordered">
            <tr>
                <td>ID</td>
                <td>名</td>
            </tr>
            {% for item in devicegrouplist %}
                <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.name}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">设备区域</h3>
        </div>
        <div class="panel-body">
            <form action='/AddBasicInfo/' method="post">
                <span>设备区域:</span>{{ deviceregionform.deviceregion }}
                <input class="btn btn-success" type="submit" value="添加"><span>{{ deviceregionstatus }}</span>
            </form>
        </div>
                <table style="text-align: center;width: 80%" class="table table-bordered">
            <tr>
                <td>ID</td>
                <td>名</td>
            </tr>
            {% for item in deviceregionlist %}
                <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.name}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
        <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">摄像头方向</h3>
        </div>
        <div class="panel-body">
            <form action='/AddBasicInfo/' method="post">
                <span>摄像头方向:</span>{{ cameradirectionform.cameradirection }}
                <input class="btn btn-success" class="btn btn-success" type="submit" value="添加"><span>{{ videodirectionstatus }}</span>
            </form>
        </div>
                    <table style="text-align: center;width: 80%" class="table table-bordered">
            <tr>
                <td>ID</td>
                <td>名</td>
            </tr>
            {% for item in cameradirectionlist %}
                <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.name}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">摄像头分类</h3>
        </div>
        <div class="panel-body">
            <form action='/AddBasicInfo/' method="post">
                <span>摄像头分类:</span>{{ cameratypeform.cameratype }}
                <input class="btn btn-success" type="submit" value="添加"><span>{{ cameratypestatus }}</span>
            </form>
        </div>
                <table style="text-align: center;width: 80%" class="table table-bordered">
            <tr>
                <td>ID</td>
                <td>名</td>
            </tr>
            {% for item in cameratypelist %}
                <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.name}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">设备品牌</h3>
        </div>
        <div class="panel-body">
            <form action='/AddBasicInfo/' method="post">
                <span>设备品牌:</span>{{ devicebrandform.devicebrand }}
                <input class="btn btn-success" type="submit" value="添加"><span>{{ devicebrandstatus }}</span>
            </form>
        </div>
                <table style="text-align: center;width: 80%" class="table table-bordered">
            <tr>
                <td>ID</td>
                <td>名</td>
            </tr>
            {% for item in devicebrandlist %}
                <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.name}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

        <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">设备型号</h3>
        </div>
        <div class="panel-body">
            <form action='/AddBasicInfo/' method="post">
                品牌:<select name="devicebrandid">
                    {% for id in devicebrandid %}
                        <option id="devicebrandid" name="devicebrandid" value="{{ id.id }}">{{ id.name }}</option>
                    {% endfor %}
                </select>
                <span>设备型号:</span>{{ devicetypeform.devicetype }}
                <input class="btn btn-success" type="submit" value="添加"><span>{{ devicetypestatus }}</span>
            </form>
        </div>
                <table style="text-align: center;width: 80%" class="table table-bordered">
            <tr>
                <td>ID</td>
                <td>brand</td>
                <td>type</td>
            </tr>
            {% for item in devicetypelist %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.brandid.name }}</td>
                    <td>{{ item.name}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>


{% endblock %}

templates/AddCameraDevice.html
{% extends "Master/muban.html" %}

{% block content %}

<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">设备查询</h3>
        </div>
        <div class="panel-body">
            <form action='/AddCameraDevice/' method="post" >
                {% for forms in form %}
                    {{ forms.label}}:{{ forms }}
                    {{ forms.error }}
                {% endfor %}
                <input type="submit" value="查询" class="btn bt-sm btn-primary radius"><span>{{ status }}</span>
            </form>
        </div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">添加摄像头</h3>
        </div>
        <div class="panel-body">
            <form action='/AddCameraDevice/' method="post" >
                {% for forms in form %}
                    {{ forms.label}}:{{ forms }}
                    {{ forms.error }}
                {% endfor %}
                <input type="submit" value="添加" class="btn bt-sm btn-primary radius"><span>{{ status }}</span>
            </form>
        </div>
    </div>

            <h1 style="text-align: center;color: beige">设备列表</h1>
            <table style="text-align: center;background: beige" class="table table-bordered">
                <tr>

                    <td>名称</td>
                    <td>区域</td>
                    <td>IP</td>
                    <td>状态</td>
                    <td>分组</td>
                    <td>方向</td>
                    <td>类型</td>
                    <td>品牌</td>
                    <td>型号</td>
                    <td>运营商</td>
                    <td>更新时间</td>
                    <td>创建时间</td>
                    <td>修改</td>
                    <td>删除</td>

                </tr>
                {% for item in cameradevice_list %}
                    <tr>

                        <td><a href="../CameraDevice/{{ item.id }}/" target="_blank">{{ item.name }}</a></td>
                        <td>{{ item.regionid.name }}</td>
                        <td>{{ item.ip}}</td>
                        <td>
                            {% if item.statusid_id == 1 %}
                                <span style="color: rgb(0, 174, 0); font-size: 18px;" class="glyphicon glyphicon-facetime-video"></span>
                            {% else %}
                                <span style="color: rgb(255, 0, 0); font-size: 18px;" class="glyphicon glyphicon-facetime-video"></span>
                            {% endif %}
                        </td>
                        <td>{{ item.groupid.name}}</td>
                        <td>{{ item.directionid.name}}</td>
                        <td>{{ item.ctypeid.name}}</td>
                        <td>{{ item.brandid.name}}</td>
                        <td>{{ item.dtypeid.name}}</td>
                        <td>{{ item.telecomid.name }}</td>
                        <td style="font-size: 10px">{{ item.updatetime|date:"Y-m-d" }}<br>{{ item.updatetime|date:"H:i:s" }}</td>
                        <td>{{ item.addtime|date:"Y-m-d" }}</td>
                        <td><a class="btn bt-sm btn-success radius" type="button" href="../UpdateCameraDevice/{{ item.id }}/" target="_blank">修改</a></td>
                        <td><a class="btn bt-sm btn-danger radius" type="button" href="../DelCameraDevice/{{ item.id }}/" target="_blank" onclick="return confirm('你确认要删除设备吗？')">删除</a></td>
                    </tr>
                {% endfor %}

            </table>
    </div>


</div>



{% endblock %}

{% block javascript %}

{% endblock %}

templates/AddThreeNetwork.html
{% extends "Master/muban.html" %}

{% block content %}
<body>
    <form action='/AddThreeNetwork/' method="post">
        部门:<select name="workgroup">
            {% for x in workgrouplist %}
                <option id="workgroup" name="workgroup" value="{{ x.id }}">{{ x.name }}</option>
            {% endfor %}
        </select>

	    <span>Vlan:</span>{{ form.vlan }}
	    <span>网关:</span>{{ form.gateway }}
	    <span>子网掩码:</span>{{ form.netmask }}

        <input type="submit" value="添加"><span>{{ status }}</span>
    </form>
    <table style="text-align: center;width: 80%" class="table table-bordered">
            <tr>
                <td>ID</td>
                <td>部门</td>
		<td>Vlan</td>
		<td>网关</td>
		<td>子网掩码</td>
            </tr>
            {% for item in threenetworklist %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td><a href="../ThreeNetwork/{{ item.id }}/">{{ item.workgroupID.name }}</a></td>
                    <td>{{ item.vlan }}</td>
		            <td>{{ item.gateway }}</td>
		            <td>{{ item.netmask }}</td>
                    <td>{{ item.statusID.status }}</td>
                </tr>
            {% endfor %}
        </table>



</body>
{% endblock %}

templates/AddWorkGroup.html
{% extends "Master/muban.html" %}

{% block content %}
<body>
    <form action='/AddWorkGroup/' method="post">
        <span>部门名称:</span>{{ form.name }}
        <br/>
        <input type="submit" value="添加"><span>{{ status }}</span>
    </form>
    <table style="text-align: center;width: 80%" class="table table-bordered">
            <tr>
                <td>ID</td>
                <td>部门名称</td>
            </tr>
            {% for item in workgrouplist %}
                <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.name }}</td>
                </tr>
            {% endfor %}

        </table>



</body>
{% endblock %}

templates/ApplyCertificate.html
{% extends "Master/muban.html" %}

{% block content %}

<div>
    <div>
        <div>
            <div class="page-form">
                <form action="/applycertificate/" method="post" class="smart-green">
                    <h1>数字证书在线申请</h1>
                    <div class="radioclass">
                        <span>申请类型</span>{{ form.ApplyType }}
                    </div>
                    <hr>
                    <label>
                        <div>{{ form.Workgroup }}</div>
                        <div id="addAddress" >
                            <div class="address_input">
                                <input class="address_input1" type="" placeholder="请选择" id="shengshi" onClick="getProvinceBuy()" readonly="readonly">
                            </div>
                        </div>
                        <div >姓名 :<input style="width: 80px;" id="name" type="text" name="name" placeholder="" /></div>
                        <div ><span>性别 :</span>
                        <select class="select">
                            <option value="none" selected="selected">请选择</option>
                            <option value="1">男</option>
                            <option value="0">女</option>
                        </select></div>
                        <div class="phone">电话 :<input id="name" type="text" name="name" placeholder="" /></div></br>
                        <div class="sfz">身份证 :<input id="name" type="text" name="name" maxlength="18" /></div>
                        <div>电子邮件 :<input id="" type="email" name=""></div>
                        <div>地址 :<input id="" type="text" name=""></div>
                        <hr/>
                    </label>
                    <label>
                        <div><span>任职 :</span>
                        <select class="select">
                            <option value="none" selected="selected">请选择</option>
                            <option value="科员">正职</option>
                            <option value="科员">副职</option>
                            <option value="科员">其它</option>

                        </select></div>
                        <div><span>职级 :</span>
                        <select class="select">
                            <option value="none" selected="selected">请选择</option>
                            <option value="科员">科员</option>
                            <option value="科员">正科</option>
                            <option value="科员">副科</option>
                        </select></div>
                        <div><span>工作岗位 :</span>
                        <select class="select">
                            <option value="none" selected="selected">请选择</option>
                            <option value="科员">科员</option>
                            <option value="科员">正科</option>
                            <option value="科员">副科</option>
                        </select></div>
                        <div><span>警种 :</span>
                        <select class="select">
                            <option value="none" selected="selected">请选择</option>
                            <option value="科员">国保</option>
                            <option value="科员">经侦</option>
                            <option value="科员">治安</option>
                            <option value="科员">边防</option>
                            <option value="科员">刑侦</option>
                            <option value="科员">出入境</option>
                            <option value="科员">消防</option>
                            <option value="科员">网警</option>
                            <option value="科员">行动技术</option>
                            <option value="科员">监所管理</option>
                            <option value="科员">交通管理</option>
                            <option value="科员">法制</option>
                            <option value="科员">装备财务</option>
                            <option value="科员">禁毒</option>
                            <option value="科员">信息通信</option>
                            <option value="科员">办公室</option>
                            <option value="科员">纪委</option>
                            <option value="科员">督察</option>
                            <option value="科员">政工</option>
                            <option value="科员">人事</option>
                            <option value="科员">机关党委</option>
                            <option value="科员">派出所</option>

                        </select></div><br>
                        <div>申请时间 :<input id="" type="datetime" name=""  /> </div>
                    </label>
                        <hr/>


                        <span>&nbsp;</span>
                        <div><input  type="submit" class="button" value="提交" /></div>

                </form>

            </div>

        </div>
    </div>
</div>

{% endblock %}

templates/CameraDevice.html
{% extends "Master/muban.html" %}

{% block content %}

<div class="container">
    <div>
        {% for item in device %}
            <h1 style="text-align: center "><font color="336699">{{ item.name }}</font></span>设备信息<span style="color: {{ st }}; font-size: 38px;" class="glyphicon glyphicon-facetime-video" title="{{ sttext }}"></span></h1>
        {% endfor %}
    </div>
    <div class="panel panel-success">
        <div class="panel-heading">
        <h3 class="panel-title" >设备详细信息</h3>
        </div>
        <div class="panel-body" style="font-size: 18px">
            {% for item in device %}
                IP地址：<a class="btn btn-primary">{{ item.ip }}</a>
                品牌：<a class="btn btn-primary">{{ item.brandid.name }}</a>
                型号：<a class="btn btn-primary">{{ item.dtypeid.name }}</a>
                设备类型：<a class="btn btn-primary">{{ item.ctypeid.name }}</a>
                方向：<a class="btn btn-primary">{{ item.directionid }}</a>
                位置：<a class="btn btn-primary">东经{{ item.gpslon }}北纬{{ item.gpswei }}</a>
                供电：<a class="btn btn-primary">{{ item.powersupply }}</a>
                运营商：<a class="btn btn-primary">{{ item.telecomid.name }}</a><br>
                后端设备：<a class="btn btn-primary">{{ item.nvrdeviceid.name }}</a>
                设备分组:<a class="btn btn-primary">{{ item.groupid.name }}</a>
            {% endfor %}
        </div>
    </div>

    <div class="panel panel-success">
        <div class="panel-heading">
        <h3 class="panel-title" >运行图表</h3>
        </div>
        <div class="panel-body" style="font-size: 18px">
            {% for item in device %}

            {% endfor %}
        </div>
    </div>
    <div class="panel panel-success">
        <div class="panel-heading">
        <h3 class="panel-title" >设备抓图</h3>
        </div>
        <div class="panel-body" style="font-size: 18px">

        </div>
    </div>
</div>



{% endblock %}

templates/ServerHost.html
{% extends "Master/muban.html" %}

{% block content %}
<body >
    <div>
        <table style="text-align: center;width: 80%" class="table table-bordered">
            <caption>
                {% for item in serverhostnamedata %}
                {{ item.hostName }}:{{ item.hostIP }}
                {% endfor %}
            </caption>
            <tr>
                <td>服务器状态</td>
                <td>最后存活时间</td>
            </tr>
            {% for item in serverhostdata %}
                <tr>
                <td>{{ item.status.status}}</td>
                <td>{{ item.updateTime|date:"Y-m-d H:i:s" }}</td>
                </tr>
            {% endfor %}

        </table>
    </div>
</body>
{% endblock %}

templates/ServerHostList.html
{% extends "Master/muban.html" %}
{% block css %}
    <meta http-equiv="refresh"content="30">
{% endblock %}
{% block content %}

<body>
    <div>
        <h1 style="text-align: center">服务器列表</h1>
        <table style="text-align: center;width: 80%" class="table table-bordered">
            <tr>
                <td>ID</td>
                <td>服务器名</td>
                <td>服务器IP</td>
                <td>服务器状态</td>
                <td>最后存活时间</td>
                <td>首次创建时间</td>
            </tr>
            {% for item in serverhostlist %}
                <tr>
                <td>{{ item.id }}</td>
                <td><a href="../ServerHost/{{ item.id }}/" target="_blank">{{ item.hostName }}</a></td>
                <td>{{ item.hostIP}}</td>
                <td>{{ item.status.status}}</td>
                <td>{{ item.updatetime|date:"Y-m-d H:i:s" }}</td>
                <td>{{ item.addtime|date:"Y-m-d H:i:s" }}</td>
                </tr>
            {% endfor %}

        </table>
    </div>
<div>

</div>
</body>
{% endblock %}

templates/UpdateDevice(非Model).html
{% extends "Master/muban.html" %}

{% block content %}
<body >
{% for camerainfo in cameradevice_ID %}
<div class="panel panel-primary">
    <div class="panel-heading">
            <h3 class="panel-title">修改设备信息</h3>
        </div>
        <div class="panel-body">
            <form action='/UpdateCameraDevice/{{ camerainfo.id }}/' method="post">
                <span class="label label-info">设备ID:</span><input id="pid" name="pid" value="{{ camerainfo.pid }}">
                <span class="label label-info">名称:</span><input id="name" name="name" value="{{ camerainfo.name }}">
                </br>
                <span  class="label label-info">分组:</span><select name="group">
                    <option id="group" name="group" value="{{ camerainfo.groupid_id }}">{{ camerainfo.groupid.name }}</option>
                    {% for g in grouplist %}
                        <option id="group" name="group" value="{{ g.id }}">{{ g.name }}</option>
                    {% endfor %}
                </select>
                <span class="label label-info">区域:</span><select name="region">
                        <option id="region" name="region" value="{{ camerainfo.regionid_id }}">{{ camerainfo.regionid.name }}</option>
                        {% for item in deviceregion_item %}
                            <option id="region" name="region" value="{{ item.id }}">{{ item.name }}</option>
                        {% endfor %}
                    </select>
                <span class="label label-info">方向:</span><select name="direction">
                        <option id="direction" name="direction" value="{{ camerainfo.directionid_id }}">{{ camerainfo.directionid.name }}</option>
                        {% for item in cameradirection_item %}
                            <option id="direction" name="direction" value="{{ item.id }}">{{ item.name }}</option>
                        {% endfor %}
                    </select>
                <span class="label label-info">分类:</span>
                <select name="vtype">
                <option id="ctype" name="ctype" value="{{ camerainfo.ctypeid_id }}">{{ camerainfo.ctypeid.name }}</option>
                    {% for item in cameratype_item %}
                        <option id="vtype" name="vtype" value="{{ item.id }}">{{ item.name }}</option>
                    {% endfor %}
                </select>

                    <span class="label label-info">品牌:</span><select name="brand">
                        <option id="devicebrand" name="devicebrand" value="{{ camerainfo.brandid_id }}">{{ camerainfo.brandid.name }}</option>
                        {% for item in devicebrand_item %}
                            <option id="devicebrand" name="devicebrand" value="{{ item.id }}">{{ item.name }}</option>
                        {% endfor %}
                    </select>
                <span class="label label-info">型号:</span>
                <select name="dtype">
                <option id="id_brand" name="brand" value="{{ camerainfo.dtypeid_id }}">{{ camerainfo.dtypeid.name }}</option>
                    {% for item in devicetype_item %}
                        <option id="id_brand" name="brand" value="{{ item.id }}">{{ item.name }}</option>
                    {% endfor %}
                </select>
                <br><br>
                <span class="label label-info">IP:</span><input id="id_ip" name="ip" type="text" value="{{ camerainfo.ip }}">
                <span class="label label-info">帐号:</span><input id="id_username" name="username" type="text" value="{{ camerainfo.username }}">
                <span class="label label-info">密码:</span><input id="id_password" name="password" type="text" value="{{ camerainfo.password }}">
                <span class="label label-info">经度:</span><input id="id_gpslon" name="gpslon" type="text" value="{{ camerainfo.gpslon }}">
                <span class="label label-info">纬度:</span><input id="id_gpswei" name="gpswei" type="text" value="{{ camerainfo.gpswei }}">
                <br/>
                <input class="btn btn-success" type="submit" value="修改"><span>{{ updatestatus }}</span>

            </form>
        </div>
    </div>
{% endfor %}
</body>

{% endblock %}

{% block javascript %}

{% endblock %}

templates/UpdateDevice.html
{% extends "Master/muban.html" %}

{% block content %}
<body >
{% for camerainfo in cameradevice_ID %}
<div class="panel panel-primary">
    <div class="panel-heading">
            <h3 class="panel-title">修改设备信息</h3>
        </div>
        <div class="panel-body">
            <form action='/UpdateCameraDevice/{{ camerainfo.id }}/' method="post">
                {{ form.pid.label }}:{{ form.pid }}
                {{ form.name.label }}:{{ form.name }}
                {{ form.group.label }}:{{ form.group }}
                {{ form.region.label }}:{{ form.region }}
                {{ form.direction.label }}:{{ form.direction }}
                {{ form.ctype.label }}:{{ form.ctype }}
                {{ form.brand.label }}:{{ form.brand }}
                {{ form.dtype.label }}:{{ form.dtype }}
                {{ form.ip.label }}:{{ form.ip }}
                {{ form.username.label }}:{{ form.username }}
                {{ form.password.label }}:{{ form.password }}
                {{ form.gpslon.label }}:{{ form.gpslon }}
                {{ form.gpswei.label }}:{{ form.gpswei }}
                {{ form.telecom.label }}:{{ form.telecom }}
                {{ form.nvrdevice.label }}:{{ form.nvrdevice }}
                <input class="btn btn-success" type="submit" value="修改"><span>{{ updatestatus }}</span>

            </form>
        </div>
    </div>
{% endfor %}
</body>

{% endblock %}

{% block javascript %}

{% endblock %}

templates/geo.html
<!DOCTYPE html>
<html>
<head>
<title>QQ JS省市区三级联动</title>
<!-- 直接使用QQ的省市区数据 -->

<script type="text/javascript" src="../static/js/workgroup.js"></script>

<!--<script type="text/javascript" src="geo.js"></script> -->
</head>
<body onload="setup();preselect('陕西省');promptinfo();">
        <form>
            <select class="select" name="province" id="s1">
              <option></option>
            </select>
            <select class="select" name="city" id="s2">
              <option></option>
            </select>
            <input id="address" name="address" type="hidden" value="" />
          <input onclick="alert(document.getElementById('address').value); return false;" type="submit" value="提交" />
        </form>
<script>

//这个函数是必须的，因为在geo.js里每次更改地址时会调用此函数
function promptinfo()
{
    var address = document.getElementById('address');
    var s1 = document.getElementById('s1');
    var s2 = document.getElementById('s2');
    address.value = s1.value + s2.value;
}

</script>
</body>
</html>

templates/login.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Title</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
    <div>
        <form action="/login/" method="post">
            用户名:<input name="username">
            <br/>
            密码:<input name="password">
            <br/>
            <input type="submit" value="登陆"><span>{{ status }}</span>
        </form>
    </div>
</body>
</html>